language: c

compiler:
  - gcc

before_install:

script: make && sudo make install && cd t && make

## whitelist
branches:
  only:
    - master

notifications:
  email:
    -  albertofanjul@gmail.com
