language: c

sudo: false

compiler:
  - gcc

before_install:

before_script:
   - export PATH=$PATH:$PWD

script: cd t && make DEfAULT_TEST_TARGET=tap

## whitelist
branches:
  only:
    - master

notifications:
  email:
    -  albertofanjul@gmail.com
