language: generic

sudo: false

before_install:

before_script:
   - export PATH=$PATH:$PWD

script: 
   - ./autogen.sh
   - cd t 
   - make check

notifications:
  email:
    -  albertofanjul@gmail.com
