#!/bin/bash

#set -xv

GIT_DIRECTORY=$(git rev-parse --git-dir)
FILE_EXCLUDE="$GIT_DIRECTORY/info/exclude"
FILE_IGNORE="$GIT_DIRECTORY/../.gitignore"
FILE_DEST="$FILE_EXCLUDE"

function help {
   cat >&2 <<EOF

Target file configuration:
   -x, --exclude    File target $FILE_EXCLUDE (default)
   -i, --ignore     File target $FILE_IGNORE
   -f, --file=FILE  Use custom target file FILE

Commands:
   -l, --list       Shows de content of target file
   -e, --edit       Opens editor for target file
   -h, --help       Shows this help

Porcelain commands:
   -a, --add=REGEX  Add REGEX to target file (must take care of shell expansion)
                     though as a verbose command for scripting

Examples:

 $ git ignore target
 $ git ignore -i .project .classpath .settings
 $ git ignore -i .idea/ '*.ipr' '*.iws' -x target
 $ git ignore -x --add '*.bak'
 $ git ignore -x -e
EOF
   exit 1
}

if [ $# == 0 ]
then 
   cat >&2 <<EOF

Faltan argumentos
EOF
   help
fi

TEMP=$(getopt -o "leha:f:ix" -l add:,list,edit,remove-last,file:,help,ignore,exclude -n $0 -- "$@")

# Se procesan los argumentos del script
eval set -- "$TEMP"

while true
do
   case "$1" in
      -a|--add)
         echo $2 >> "$FILE_DEST" 
         shift 
         ;;
      -f|--file)
         FILE_DEST="$2" 
         shift 
         ;;
      -x|--exclude)
         FILE_DEST="$FILE_EXCLUDE" 
         ;;
      -i|--ignore)
         FILE_DEST="$FILE_IGNORE" 
         ;;
      -l|--list) 
         cat $FILE_DEST
         exit 0;;
      -e|--edit)
         vi $FILE_DEST
         exit 0;;   
      --remove-last)
         sed -i '$d' $FILE_DEST
         exit 0;;   
      -h) # --help is captured by git and converted in git help ...
         help ;;
      --) 
         shift
         for param
         do
            echo $param >> "$FILE_DEST" 
         done   
         break ;;
      *) 
         cat <&2 <<EOF

Error, argumentos $@ desconocidos
EOF
         exit 1 ;;
   esac
   shift
done

